name = "Box2D"
uuid = "a3fb879c-28ba-11e9-38dd-c70b6b05964a"
authors = ["Zenna Tavares <zennatavares@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
